[package]
name = "navi"
version = "2.1.1"
authors = ["Denis Isidoro <denis_isidoro@live.com>"]
edition = "2018"
description = "An interactive cheatsheet tool for the command-line"
homepage = "https://github.com/denisidoro/navi"
documentation = "https://github.com/denisidoro/navi"
repository = "https://github.com/denisidoro/navi"
keywords = ["cheatsheets", "terminal", "cli", "tui", "shell"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[dependencies]
regex = "1.3.4"
structopt = "0.3"
termion = "1.5.5"
raw_tty = "0.1.0"
lazy_static = "1.4.0"
dirs = "2.0.0"
terminal_size = "0.1.10"
git2 = "0.10.0"
walkdir = "2"

[features]
default = []

[[bin]]
bench = false
path = "src/main.rs"
name = "navi"
