[package]
name = "navi"
version = "2.0.0"
authors = ["Denis Isidoro <denis_isidoro@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
structopt = "0.3"
termion = "1.5.5"