[package]
name = "navi"
version = "2.10.0"
authors = ["Denis Isidoro <denis_isidoro@live.com>"]
edition = "2018"
description = "An interactive cheatsheet tool for the command-line"
homepage = "https://github.com/denisidoro/navi"
documentation = "https://github.com/denisidoro/navi"
repository = "https://github.com/denisidoro/navi"
keywords = ["cheatsheets", "terminal", "cli", "tui", "shell"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = { repository = "denisidoro/navi", branch = "master" }

[dependencies]
regex = "1.3.9"
structopt = "0.3.17"
termion = "1.5.5"
raw_tty = "0.1.0"
lazy_static = "1.4.0"
dirs = "3.0.1"
terminal_size = "0.1.13"
walkdir = "2.3.1"
shellwords = "1.1.0"
anyhow = "1.0.32"
thiserror = "1.0.20"
strip-ansi-escapes = "0.1.0"

[lib]
name = "navi"
path = "src/lib.rs"

[[bin]]
name = "navi"
path = "src/bin/main.rs"
bench = false
