# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
orbs:
  shellcheck: 'circleci/shellcheck@0.7.0'

job_defaults: &defaults
    docker:
      - image: frolvlad/alpine-bash
    working_directory: ~/repo
    environment:
      ENVIRONMENT: "test"
      TERM: "dumb"

jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: ./test/find_cheats

workflows:
  version: 2
  run-tests:
    jobs:
      - tests
  shellcheck:
    jobs:
      - shellcheck/check:
          exclude: './cheats/*'
      - shellcheck/check:
          pattern: 'navi'
      - shellcheck/check:
          pattern: '*'
          path: ./scripts/