name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        target: [x86_64-osx, aarch64-unknown-linux-musl, armv7-unknown-linux-musleabihff, armv7-linux-androideabi, x86_64-pc-windows-gnu]
        include:
          - os: macos-latest
            target: x86_64-osx
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihff
          - os: ubuntu-latest
            target: armv7-linux-androideabi
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu

    steps:
    - uses: hecrj/setup-rust-action@v1.3.1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: scripts/action release ${{ matrix.target }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/tar/navi.tar.gz
        asset_name: navi-${{ matrix.asset_name }}.tar.gz
        tag: ${{ github.ref }}