name: Publish

on: [push]

jobs:
  binary:
    name: Publish ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
    steps:
      - uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: stable
      - uses: actions/checkout@v1
      - name: Build
        id: build
        run: scripts/dot rust release ${{ matrix.target }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Install target
        id: installtarget
        run: rustup target add ${{ matrix.target }}
      # - name: Upload binaries to release
      #   uses: svenstaro/upload-release-action@v1-release
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: target/tar/navi.${{ steps.build.outputs.EXTENSION }}
      #     tag: ${{ github.ref }}
      #     asset_name: navi-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.${{ steps.build.outputs.EXTENSION }}
