name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This should work with only the `include`s but it currently doesn't because of this bug:
        # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: navi.tar.gz
            asset_name: navi-linux-amd64.tar.gz
            target: aarch64-unknown-linux-musl
          - os: macos-latest
            artifact_name: navi.tar.gz
            asset_name: navi-osx-amd64.tar.gz
            target: 

    steps:
    - uses: hecrj/setup-rust-action@v1.3.1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: scripts/release ${{ matrix.target }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/tar/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}