name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # This should work with only the `include`s but it currently doesn't because of this bug:
      # https://github.community/t5/How-to-use-Git-and-GitHub/GitHub-Actions-Matrix-options-dont-work-as-documented/td-p/29558
      os: [ubuntu-latest, windows-latest, macos-latest]
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: navi
            asset_name: navi-linux-amd64
          - os: windows-latest
            artifact_name: navi.exe
            asset_name: navi-windows-amd64
          - os: macos-latest
            artifact_name: navi
            asset_name: navi-macos-amd64

    steps:
    - uses: hecrj/setup-rust-action@v1-release
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}